proxy:
  secretToken: "774629f880afc0302830c19a9f09be4f59e98b242b65983cea7560e828df2978"
hub:
  uid: 1000
  cookieSecret: "774629f880afc0302830c19a9f09be4f59e98b242b65983cea7560e828df2978"
  db:
    type: postgres
    url: postgres+psycopg2://myadmin@<JUPYTERDBSERVERNAME>:<POSTGRESPASSWORD>@<JUPYTERDBSERVERNAME>.postgres.database.azure.com:5432/jupyterhub
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: 177037d09156
  storage:
    dynamic:
      storageClass: azurefile
rbac:
   enabled: true
auth:
  type: dummy
  dummy: 
    password: '<PASSWORD>'
  admin:
    users:
      - <USERNAME>