apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0600
  - uid=1000
  - gid=100
parameters:
  skuName: Standard_LRS
  location: westeurope
  storageAccount: jupyterstoragejdik



